apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.8.72
    helm:
      values: |
        controller:
          serviceType: ClusterIP
          admin:
            user: admin
            password: pion@1208
          resources:
            requests: { cpu: "500m", memory: "1Gi" }
            limits:   { cpu: "2",   memory: "4Gi" }
        persistence:
          enabled: true
          storageClass: 
          size: 20Gi
        rbac:
          create: true
        serviceAccount:
          create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
