gateways:
  istio-ingressgateway:
    enabled: true
    service:
      ports:
        - port: 80
          targetPort: 8080
          name: http2
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "dedicated"
    operator: "Equal"
    value: "worker"
    effect: "NoSchedule"