cr:
  create: true
  spec:
    deployment:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "dedicated"
          operator: "Equal"
          value: "worker"
          effect: "NoSchedule"
    external_services:
      prometheus:
        url: "http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "dedicated"
    operator: "Equal"
    value: "worker"
    effect: "NoSchedule"
deployment:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "dedicated"
      operator: "Equal"
      value: "worker"
      effect: "NoSchedule"