# ───── 클러스터 기본 ──────────────────────────────────────────
clusterName: "elasticsearch"
nodeGroup: "main"
masterService: "elasticsearch-main"

roles:
  - master
  - data
  - ingest

replicas: 3            # ← 3 노드
minimumMasterNodes: 2  # 2n+1 규칙

esMajorVersion: ""

# ───── 이미지 ────────────────────────────────────────────────
image: "docker.elastic.co/elasticsearch/elasticsearch"
imageTag: "8.5.1"
imagePullPolicy: "IfNotPresent"

# ───── 네트워크 - HTTP 전용 ──────────────────────────────────
protocol: http          # TLS 끔
httpPort: 9200
transportPort: 9300

service:
  enabled: true
  type: ClusterIP
  port: 9200

# ───── 리소스 / JVM ─────────────────────────────────────────
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

esJavaOpts: "-Xms1g -Xmx1g"

# ───── 스토리지 ─────────────────────────────────────────────
persistence:
  enabled: true
  size: 30Gi

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  storageClass: "local-storage"  # 로컬 스토리지 사용
  resources:
    requests:
      storage: 30Gi

# ───── 스케줄링 (taint & nodeSelector) ──────────────────────
nodeSelector:
  env: dev

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "dedicated"
    operator: "Equal"
    value: "worker"
    effect: "NoSchedule"
antiAffinity: "soft"

# ───── Elasticsearch 설정 ──────────────────────────────────
clusterHealthCheckParams: "wait_for_status=green&timeout=1s"
secret:
  enabled: false          # TLS·비밀번호 시크릿 생성 OFF
esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false
    xpack.security.http.ssl.enabled: false
    xpack.security.transport.ssl.enabled: false

# ───── 기타 ─────────────────────────────────────────────────
tests:
  enabled: false        # Helm 테스트 Job 생략
sysctlInitContainer:
  enabled: true         # vm.max_map_count 262144 세팅