# ------------------------------------------------------------
# 공통 toleration – 필요한 곳마다 *efk_tolerations 로 재사용
# ------------------------------------------------------------
efk_tolerations: &efk_tolerations
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "dedicated"
    operator: "Equal"
    value: "worker"
    effect: "NoSchedule"

# ------------------------------------------------------------
# Bitnami Elasticsearch
# ------------------------------------------------------------
global:
  kibanaEnabled: false          # Kibana는 별도 차트 사용
  imageRegistry: docker.io

clusterName: efk

image:
  registry: docker.io
  repository: bitnami/elasticsearch
  tag: 9.0.3-debian-12-r1
  pullPolicy: IfNotPresent

security:                        # X-Pack / TLS 모두 끔 (HTTP only)
  enabled: false
  tls:
    enabled: false

master:
  replicaCount: 1
  masterOnly: true
  tolerations: *efk_tolerations
  persistence:
    enabled: true
    storageClass: gp2            # 필요하면 수정
    size: 20Gi
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

data:
  replicaCount: 2
  tolerations: *efk_tolerations
  persistence:
    enabled: true
    storageClass: local-storage
    size: 30Gi
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

coordinating:
  replicaCount: 1
  tolerations: *efk_tolerations
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

ingest:
  enabled: false                # 필요 시 true