# ------------------------------------------------------------
# Bitnami Fluent Bit
# ------------------------------------------------------------
image:
  registry: docker.io
  repository: bitnami/fluent-bit
  tag: 3.0.3-debian-11-r0
  pullPolicy: IfNotPresent

daemonset:
  enabled: true
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "dedicated"
      operator: "Equal"
      value: "worker"
      effect: "NoSchedule"

  # 로그 경로 마운트 예시 (Docker, containerd 둘 다 커버)
  hostPathMounts:
    - name: varlog
      hostPath: /var/log
      mountPath: /var/log
    - name: containers
      hostPath: /var/lib/docker/containers      # containerd면 /var/log/pods 로 변경
      mountPath: /var/lib/docker/containers
      readOnly: true

backend:
  type: es
  es:
    host: elasticsearch
    port: 9200
    logstash_prefix: fluentbit
    tls: "off"
    http_user: ""            # ES 보안 OFF
    http_passwd: ""
    replace_dots: "On"       # Kubernetes label에서 . → _

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi