# ------------------------------------------------------------
# Bitnami Fluent Bit
# ------------------------------------------------------------
image:
  registry: docker.io
  repository: bitnami/fluent-bit
  tag: 4.0.4-debian-12-r0
  pullPolicy: IfNotPresent

daemonset:
  enabled: true
  hostPaths:
    logs: /var/log
    containerLogs: /var/log/containers   # containerd 표준
    machineId: /etc/machine-id

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "dedicated"
    operator: "Equal"
    value: "worker"
    effect: "NoSchedule"

# 로그 경로 마운트 예시 (Docker, containerd 둘 다 커버)

backend:
  type: es
  es:
    host: elasticsearch
    port: 9200
    logstash_prefix: fluentbit
    tls: "off"
    http_user: ""            # ES 보안 OFF
    http_passwd: ""
    replace_dots: "On"       # Kubernetes label에서 . → _

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

config:
  ## --- Service 블록 ---
  service: |
    [SERVICE]
        Flush           1
        Daemon          Off
        Log_Level       info
        HTTP_Server     On
        HTTP_Listen     0.0.0.0
        HTTP_Port       {{ .Values.containerPorts.http }}
        Parsers_File    parsers.conf
        Config_Watch    On
  ## --- Input: Tail ---
  inputs: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            cri
        Refresh_Interval  5
        Rotate_Wait       30
        DB                /fluent-bit/tail-db/tail-containers.db
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On
  ## --- Filter: Kubernetes 메타데이터 ---
  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
  ## --- Output: Elasticsearch ---
  outputs: |
    [OUTPUT]
        Name            es
        Match           *
        Host            elasticsearch
        Port            9200
        Logstash_Format On           # → 인덱스: fluentbit-YYYY.MM.DD
        Replace_Dots    On
        Retry_Limit     False
        tls             Off