apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: elasticsearch
    targetRevision: 22.0.13   # 2025-07-16 기준 최신 안정판  [oai_citation:4‡Artifact Hub](https://artifacthub.io/packages/helm/bitnami/elasticsearch?utm_source=chatgpt.com)
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/RedForest0607/onpremise-cluster/main/dev/argo-values/efk/elasticsearch/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: efk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true