apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.elastic.co'
    chart: kibana
    targetRevision: 8.5.1
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/RedForest0607/onpremise-cluster/main/dev/argo-values/efk/kibana/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: efk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true