replicaCount: 1

image: "docker.elastic.co/kibana/kibana"
imageTag: "8.5.1"
imagePullPolicy: "IfNotPresent"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

protocol: http

service:
  type: ClusterIP
  port: 5601

elasticsearchHosts: "http://elasticsearch-master.default.svc.cluster.local:9200"

nodeSelector:
  env: dev

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "dedicated"
    operator: "Equal"
    value: "worker"
    effect: "NoSchedule"

affinity: {}