# ------------------------------------------------------------
# Bitnami Kibana
# ------------------------------------------------------------
image:
  registry: docker.io
  repository: bitnami/kibana
  tag: 9.0.3-debian-12-r0
  pullPolicy: IfNotPresent

elasticsearch:                  # 외부 ES 서비스 정보
  hosts:
    - elasticsearch
  port: 9200
  protocol: http
  security:
    auth:
      enabled: false
    tls:
      enabled: false

service:
  type: ClusterIP
  port: 5601

ingress:
  enabled: false                # 필요하면 true & rules 설정

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "dedicated"
    operator: "Equal"
    value: "worker"
    effect: "NoSchedule"

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi